import NPuzzle


print("Manhattan only")
print("3 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('3puzzle.txt')
print(x.search())
print()
print("8 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('8puzzle.txt')
print(x.search())
print()
print("15 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('15puzzle.txt')
print(x.search())
print()
print("24 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('24puzzle.txt')
print(x.search())

print()
print("Both Heuristics")
print("3 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('3puzzle.txt')
print(x.search_both())
print()
print("8 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('8puzzle.txt')
print(x.search_both())
print()
print("15 puzzle")
x = NPuzzle.NPuzzle()
x.initialize('15puzzle.txt')
print(x.search_both())
print()
print('24 puzzle')
x = NPuzzle.NPuzzle()
x.initialize('24puzzle.txt')
print(x.search_both())